language: node_js
matrix:
  include:
    - node_js: "0.12"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony'"
    - node_js: "iojs"
    - node_js: "iojs-v1.0.4" # earlier version of iojs

script: "mocha -b $NODE_FLAGS test/build"
