language: node_js
matrix:
  include:
    - node_js: "0.12"
      env: "NODE_FLAGS=''"
    - node_js: "0.11"
      env: "NODE_FLAGS='--harmony --harmony-generators'"
    - node_js: "iojs"
    - node_js: "iojs-v1.0.4" # earlier version of iojs
